const GET_SUPER_HEROES = 'GET_SUPERHEROES';
const GET_SUPER_HEROES_SUCCESS = 'GET_SUPERHEROES_SUCCESS';
const GET_SUPER_HEROES_FAIL = 'GET_SUPERHEROES_FAIL';
const GET_SINGLE_HERO = 'GET_SINGLE_HERO';
const GET_SINGLE_HERO_SUCCESS = 'GET_SINGLE_HERO_SUCCESS';
const GET_SINGLE_HERO_FAIL = 'GET_SINGLE_HERO_FAIL';

export {
  GET_SUPER_HEROES,
  GET_SUPER_HEROES_SUCCESS,
  GET_SUPER_HEROES_FAIL,
  GET_SINGLE_HERO,
  GET_SINGLE_HERO_SUCCESS,
  GET_SINGLE_HERO_FAIL,
};
